### ISSUE TITLE
TypeError: Cannot read property 'help' of undefined

### ISSUE THREAD

**Issue by blacksmoke26** [chmontgomery/gulp-help#48]
Error found:

```
> gulp
G:\WebData\wwwroot\someweb\node_modules\gulp-help\index.js:81
    task = gulp.tasks[name];
                     ^
TypeError: Cannot read property 'help' of undefined
    at Gulp.gulp.task (G:\WebData\wwwroot\someweb\node_modules\gulp-help\index.js:81:22)
    at module.exports (G:\WebData\wwwroot\someweb\node_modules\gulp-help\index.js:97:8)
    at Object.<anonymous> (G:\WebData\wwwroot\someweb\gulpfile.js:11:29)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)```

**Comment by Enkrod** [comment]
Are you using Gulp v4 or Gulp v3? 

Because the master-branch only works with Gulp V3

**Comment by blacksmoke26** [comment]
oh,  am using Gulp v4! Are you going to fix for V3?

Pulling V3 is not possible ATM, so `npm update` is messing up everything.

**Comment by Enkrod** [comment]
Install gulp-help via `npm install github:chmontgomery/gulp-help#gulp4`

Sadly I cannot fix anything because this is not my project, I am only some guy who had the same problem as you.

In the long run gulp-help should be replaced by `gulp -T` or `gulp --tasks-simple` the main difference right now is that `gulp --tasks-simple` does not support descriptions.

**Comment by akomm** [comment]
So basically gulp has become garbage, because it does not work with newer node versions in V3 and if you upgrade to V4 other stuff, like this is not working and broken (when I remove gulp-help require, it continues failing on other sides).

**Comment by fbolaji** [comment]
Any solution to gulp issue above because I am experiencing the same issue

**Comment by CyberSecDemon** [comment]
Yeah this is jacked. Gulp is trash.

**Comment by bdbowen** [comment]
For anyone else still trying to figure it out, it looks like there is a temporary package version of this package that works with gulp4. Eventually they should make `gulp --task-simple` work for this instead (Enkrod, above), but it doesn't appear to be working yet. Here is the link: https://www.npmjs.com/package/gulp-help-four
