### ISSUE TITLE
gulp-help#gulp4  not working with  gulp 4.0.2

### ISSUE THREAD

**Issue by gad0lin** [chmontgomery/gulp-help#52]
#gulpfile
const gulp = require('gulp-help')(require('gulp'));
gulp.task('plist', 'list processes', async function () {
    console.log('Hello World')
});

#package.json

{
  "name": "hello",
  "version": "1.0.0",
  "description": "JHello",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": "~12.10.0"
  },
  "keywords": [
    "hello"
  ],
  "author": "kb",
  "license": "N/A",
  "dependencies": {
    "gulp": "^4.0.2",
    "gulp-help": "https://github.com/chmontgomery/gulp-help.git#gulp4"
  }
}

# error

assert.js:373
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (node_modules/undertaker/lib/task.js:13:8)
    at Gulp.gulp.task (node_modules/gulp-help/index.js:40:33)
    at Object.<anonymous> gulpfile.js:2:6)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

# node version 12.10.0

**Comment by echernyavskiy** [comment]
Workaround:

```javascript
(() => {
  let myTask = () => {
    return gulp
      .src(['*'], {allowEmpty: true})
      .pipe(foo());
  };
  myTask.description = 'This is my task.';

  gulp.task('my-task', myTask);
})();
```
